name: "beat_detector"
version: "1.0.0"
architecture:
  input_channels: 1
  hidden_channels: [16, 32, 64]
  kernel_sizes: [15, 15, 15]
  pool_sizes: [2, 2, 1]

training_params:
  optimizer:
    name: "Adam"
    params:
      lr: 0.001
      weight_decay: 0.0001
  
  scheduler:
    name: "ReduceLROnPlateau"
    params:
      mode: "min"
      factor: 0.5
      patience: 5
  
  criterion:
    name: "BCELoss"
    params: {}
  
  batch_size: 32
  num_epochs: 100
  early_stopping_patience: 10

weights_path: "models/weights/beat_detector_v1.pt" 